name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Deploy on push to the main branch (change if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Adjust to match your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Vercel CLI
      run: |
        npm install -g vercel

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{'V5f9bBEDQx70m8fILDZ8wmiW'}}
      run: |
        vercel login $VERCEL_TOKEN
        vercel --prod --confirm
