version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Adjust if the Dockerfile has a different name
    container_name: backend_service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app  # Mounts the root directory where app.py is located
    depends_on:
      - database

  database:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  frontend:
    image: nginx:alpine
    container_name: nginx_frontend
    ports:
      - "80:80"
    volumes:
      - ./templates:/usr/share/nginx/html  # Adjust path if your templates are stored elsewhere

networks:
  default:
    driver: bridge
